### ISSUE TITLE
Cannot use `gpg.format=ssh` when set globally on git config

### ISSUE THREAD

**Issue by jonesbusy** [jenkinsci/plugin-modernizer-tool#107]
### What feature do you want to see added?

I'm using my SSH key to sign my commits (it's set globally) (See https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key#telling-git-about-your-ssh-key)

Doesn't seem to work with JGit

Nothing to fix it here but just to track this is a limitation for now.

This is tracked by https://github.com/eclipse-jgit/jgit/issues/44

There is also a PR open on gerrithub but not sure when maintainers will take a look at it https://eclipse.gerrithub.io/c/eclipse-jgit/jgit/+/1197035

```
Failed to process plugin: ansible 
java.lang.IllegalArgumentException: Invalid value: gpg.format=ssh
        at org.eclipse.jgit.lib.DefaultTypedConfigGetter.getEnum(DefaultTypedConfigGetter.java:103)
        at org.eclipse.jgit.lib.Config.getEnum(Config.java:454)
```

### Upstream changes

Only https://eclipse.gerrithub.io/c/eclipse-jgit/jgit/+/1197035 and https://github.com/eclipse-jgit/jgit/issues/44

**Comment by jonesbusy** [comment]
https://eclipse.gerrithub.io/c/eclipse-jgit/jgit/+/1197035 was merged

We should expect it on next release (hope soon)
